# Gz bridge to spwan entities
- ros_topic_name: "spawn_entity"
  gz_topic_name: "world/test_approach/create"
  ros_type_name: "ros_gz_interfaces/msg/EntityFactory"
  gz_type_name: "gz.msgs.EntityFactory"
  direction: ROS_TO_GZ



- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

  
# Gz topic published by Sensors plugin (Camera)
- ros_topic_name: "camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# RGB image topic bridged
- ros_topic_name: "camera/image"
  gz_topic_name: "camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Depth image topic bridged
- ros_topic_name: "camera/depth_image"
  gz_topic_name: "camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Point cloud topic bridged
- ros_topic_name: "camera/points"
  gz_topic_name: "camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


# Gz topic published by Sensors plugin (Stationary Camera)
- ros_topic_name: "/stationary_camera/camera_info"
  gz_topic_name: "/world/EV_scenario/model/stationary_camera_model/link/stationary_camera_optical_link/sensor/fixed_rgbd_sensor/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Stationary RGB image topic bridged
- ros_topic_name: "/stationary_camera/image"
  gz_topic_name: "/world/EV_scenario/model/stationary_camera_model/link/stationary_camera_optical_link/sensor/fixed_rgbd_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Stationary Depth image topic bridged
- ros_topic_name: "/stationary_camera/depth_image"
  gz_topic_name: "/world/EV_scenario/model/stationary_camera_model/link/stationary_camera_optical_link/sensor/fixed_rgbd_sensor/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Stationary Point cloud topic bridged
- ros_topic_name: "/stationary_camera/depth_points"
  gz_topic_name: "/world/EV_scenario/model/stationary_camera_model/link/stationary_camera_optical_link/sensor/fixed_rgbd_sensor/depth_points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
